CREATE TABLE mlb_data (
	id SERIAL PRIMARY KEY,
	year INT,
  	team VARCHAR(30) NOT NULL,
  	team_salary VARCHAR(30),
  	avg_player_salary VARCHAR(30),
  	median_player_salary VARCHAR(30),
	wins INT,
	cost_per_win VARCHAR(30),
	championship BOOLEAN
);

CREATE TABLE Salaries (
	id SERIAL PRIMARY KEY,
	yearID INT,
  	teamID VARCHAR(30) NOT NULL,
  	lgID VARCHAR(30) NOT NULL,
  	playerID VARCHAR(30) NOT NULL,
  	salary INT
);

CREATE TABLE Teams (
	id SERIAL PRIMARY KEY,
	yearID INT,
  	lgID VARCHAR(30) NOT NULL,
	teamID VARCHAR(30) NOT NULL,
  	franchID VARCHAR(30) NOT NULL,
	divID VARCHAR(30),
	Ranks INT,
	Gs INT,
	Ghome INT,
	W INT,
	L INT,
	DivWin Boolean,
	WCWin Boolean,
	LgWin Boolean,
	WSWin Boolean,
	R INT,
	AB INT,
	H INT,
	two_B INT,
	three_B INT,
	HR INT,
	BB INT,
	SO INT,
	SB INT,
	CS INT,
	HBP INT,
	SF INT,
	RA INT,
	ER INT,
	ERA VARCHAR(30) NOT NULL,
	CG INT,
	SHO INT,
	SV INT,
	IPouts INT,
	HA INT,
	HRA INT,
	BBA INT,
	SOA INT,
	E INT,
	DP INT,
	FP VARCHAR(30) NOT NULL,
	team_name VARCHAR(30) NOT NULL,
	park VARCHAR(30) NOT NULL,
	attendance INT,
	BPF INT,
	PPF INT,
	teamIDBR VARCHAR(30) NOT NULL,
	teamIDlahman45 VARCHAR(30) NOT NULL,
	teamIDretro VARCHAR(30) NOT NULL
);